### ISSUE TITLE
set value of a model's property to unique

### ISSUE THREAD

**Issue by kynwu** [jedireza/hapi-mongo-models#35]
I have two questions relative to this issue.

##### How can I set certain property value of a model to unique?
for example: if I have below schema, SurrogateData collection will store 'san' which is a value being used to replace pan (real credit card number according to EMVCo spec.). The san itself should not be duplicated!

```javascript
SurrogateData.schema = Joi.object().keys({
  _id: Joi.object(),
  san: Joi.string().regex(/^\d{16}/).length(16).required(),
  expr: Joi.string().regex(/\d{4}/).length(4).required(),
  // ManyToOne
  primary_data: Joi.object().keys({
    id: Joi.string().required(),
    pan: Joi.string().regex(/\d{13,19}/).required()
  }).required()
}).required();
```
Is it correct to use below technique to achieve this?

```javascript
SurrogateData.indexes = [
    [{ san: 1 }]
];
```

##### What's the best strategy under this context to generate a non-duplicated san and insert into collection? Now, I do the following steps:
a. generateSan()
b. checkDuplicated() (if duplicated then go to step a)
c. insert()

**Comment by jedireza** [comment]
Thanks for opening an issue.

> Is it correct to use below technique to achieve this?

Not exactly. We need to add the options object like this:

```js
SurrogateData.indexes = [
    [{ san: 1 }, { unique: true }]
];
```

There are a bunch of options that can be passed in that second object: http://mongodb.github.io/node-mongodb-native/2.0/api/Collection.html#ensureIndex

> What's the best strategy under this context to generate a non-duplicated san and insert into collection? Now, I do the following steps:

Those steps seem fine. Checking for a  duplicate is more elegant than seeing if an insert failed (because of the unique index) and trying to inspect the error details to communicate the right message to the caller/end-user.
