### ISSUE TITLE
Can't use Mongo Native method Aggregate

### ISSUE THREAD

**Issue by Sriram-27727** [jedireza/hapi-mongo-models#58]
If am using aggregate method on my collection it gives me error

ebug: internal, implementation, error 
    TypeError: Uncaught error: ClientStatus.aggregate is not a function
    at server.route.config.pre.method.reply (

**Comment by jedireza** [comment]
Thanks for opening an issue. Since we don't expose a `aggregate` method in the base class, it'll be up to you to create one on your model(s).

Or, we could extend the base class to expose the `aggregate` method of the underlying collection like we did in #23 for the `distinct` method.

Another thought would be to create a getter so we can access the underlying collection and use it directly. (Ex: `MyClass.getCollection()`)

**Comment by svnlto** [comment]
Just expose it like `distinct`.

**Comment by jedireza** [comment]
[`mongo-models` was updated](https://github.com/jedireza/mongo-models/pull/2) to expose the `aggregate` method and was published as `mongo-models@1.1.0`.

https://github.com/jedireza/mongo-models/pull/2
