### ISSUE TITLE
Not authorized on dbname to execute command

### ISSUE THREAD

**Issue by jgauna** [jedireza/hapi-mongo-models#59]
If I try to find multiple registries inside an ```async.each``` loop, just sometimes, I get ```Not authorized on dbname to execute command```. If it's a security issue I should get the "Not authorized" error always but this is not the case. On the other side, I'm connecting to a vps and if I disable ```auth=true``` from Mongo on the server it works correctly.

model.js
```
async.each(result, function(order, next) {
  AnotherModel.findOne({shop_id: shopId}, function(err, shop) {
    // Sometimes I get err, otherwise the registry
  });
});
```

Any help ? Thanks

**Comment by jedireza** [comment]
Thanks for opening an issue.

> If I try to find multiple registries inside an ```async.each``` loop, just sometimes, I get ```Not authorized on dbname to execute command```

If we're unable to reproduce the issue consistently it becomes much harder to diagnose. Also, since it seems to work sometimes I predict the issue isn't with this repo.

Also based on the code snippet you shared I'm unable to get a bigger picture of what you're trying to accomplish. If you're willing to provide more details there it may help.
