### ISSUE TITLE
Issue with updateOne & update Many

### ISSUE THREAD

**Issue by bryandent** [jedireza/hapi-mongo-models#62]
It seems that for some reason we are unable to update a model.  No issues with creating, finding, etc.

Using something as simple as the following code, yields a count = 0:

```
Company.updateOne({ _id: '57c9a2894160eb694371d69d' }, { $set: { name: 'TEST' } }, (err, count) => {
      if(err){
        return reply(Boom.wrap(err, 500));
      }

      reply({ count: count });
    }); 
```

Is there something that is being overlooked here?  I've also looked at the test code and everything seems to be lined up correctly.

**Comment by bryandent** [comment]
I've gotten around this issue by just using the findByIdAndUpdate function on the model.  Still interested why the update method doesn't work though.

**Comment by jedireza** [comment]
I think what you're experiencing is due to the value type of `_id`. See: https://github.com/jedireza/hapi-mongo-models#_idclass

And you can see in the source of `findById`, `findByIdAndUpdate` and `findByIdAndDelete`, they all cast the `_id` parameter to the `Collection._idClass` type you define (and defaults to `MongoDB.ObjectId`). Ex: https://github.com/jedireza/hapi-mongo-models/blob/a6655b104a36447979e2cc39adc139631d06709c/lib/base-model.js#L379-L384

**Comment by bryandent** [comment]
Ah, makes sense.  Thanks for getting back to me. Appreciate it.

**Comment by jedireza** [comment]
Oh I just remembered. We keep a reference to `MongoDB.ObjectId` available on all models for convenience. See https://github.com/jedireza/hapi-mongo-models#objectid

This way you don't have to `require('mongodb')` to access it in your code.

```js
const query = {
    _id: Company.ObjectId('57c9a2894160eb694371d69d')
};

Company.updateOne(query, { $set: { name: 'TEST' } }, (err, count) => {
    if(err){
        return reply(Boom.wrap(err, 500));
    }

    reply({ count: count });
});
```

Just remember that if you define a different `_idClass` to use that instead.

```js
const query = {
    _id: Company._idClass('some-custom-type')
};
```

And if your `_id` fields are just strings, you can just use a plain string.

```js
const query = {
    _id: 'a-string-value'
};
```
